FROM ubuntu:16.04

# INSTALL DEPENDENCIES
RUN apt-get update -y && apt-get install -y python-pip python-setuptools openssl python-dev libssl-dev cron
RUN pip install pip==20.3.3

ADD . /srv
WORKDIR /srv

RUN pip install -r requirements.txt

# run the command on container startup
CMD python /srv/crawler.py /srv/